import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Soul AI Agents",
  description: "Terms of Service and usage guidelines for Soul AI Agents",
};

export default function Terms() {
  return (
    <div className="container mx-auto px-4 py-24">
      <h1 className="text-4xl font-bold mb-8 gradient-text">
        Terms of Service
      </h1>

      <div className="prose prose-invert max-w-none">
        <p className="text-lg mb-6">
          Last updated:{" "}
          {new Date().toLocaleDateString("en-US", {
            month: "long",
            day: "numeric",
            year: "numeric",
          })}
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Service Overview</h2>
          <p>
            Soul Agents Trading Platform ("Platform") provides AI-powered
            cryptocurrency trading insights through GIGABRAIN AI technology.
            This service includes chat interfaces, market analysis, and trading
            suggestions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. User Eligibility</h2>
          <ul className="list-disc pl-6">
            <li>Users must be of legal age in their jurisdiction</li>
            <li>
              Users must have basic understanding of cryptocurrency trading
            </li>
            <li>Access is password-protected and by invitation only</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            3. AI Trading Insights
          </h2>
          <ul className="list-disc pl-6">
            <li>All trading suggestions are generated by AI</li>
            <li>
              Platform uses multiple data sources including Arbitrum, Base, and
              Ethereum networks
            </li>
            <li>
              Network status monitoring is provided but not guaranteed to be
              real-time
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            4. Intellectual Property
          </h2>
          <ul className="list-disc pl-6">
            <li>
              All content, including AI responses, UI elements, and branding
              materials are proprietary
            </li>
            <li>
              The GIGABRAIN AI system and Crypto Bunny brand are protected
              intellectual property
            </li>
            <li>
              Users may not scrape, copy, or redistribute platform content
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. User Conduct</h2>
          <ul className="list-disc pl-6">
            <li>No automated access or bot interactions</li>
            <li>No attempts to bypass security measures</li>
            <li>No sharing of access credentials</li>
            <li>Respect rate limits and platform restrictions</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            6. Service Modifications
          </h2>
          <p>We reserve the right to:</p>
          <ul className="list-disc pl-6">
            <li>Modify or terminate services</li>
            <li>Update AI models and trading algorithms</li>
            <li>Change network connections and data sources</li>
            <li>Modify interface elements and features</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Termination</h2>
          <p>We may terminate access for:</p>
          <ul className="list-disc pl-6">
            <li>Violation of these terms</li>
            <li>Suspicious trading activity</li>
            <li>Sharing of access credentials</li>
            <li>Any activity deemed harmful to the platform</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
